services:
  - type: web
    name: multiple-cognitive-task
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0

